# SonarQube configuration for EuskalIA Server
sonar.projectKey=EuskalIA.Server
sonar.projectName=EuskalLingo Server
sonar.projectVersion=1.0

# Path to source files
sonar.sources=.
sonar.language=cs
sonar.sourceEncoding=UTF-8

# Exclude test files
sonar.exclusions=**/Migrations/**, **/bin/**, **/obj/**, **/Tests/**

# Results of unit tests
# sonar.cs.vstest.reportsPaths=**/TestResults/*.trx
# sonar.cs.opencover.reportsPaths=**/TestResults/*/coverage.opencover.xml
