namespace EuskalIA.Server.DTOs.AI
{
    /// <summary>Root object for the Gemini API response.</summary>
    public class GeminiResponse
    {
        /// <summary>Gets or sets the list of candidates generated by the model.</summary>
        public List<Candidate>? Candidates { get; set; }
    }

    /// <summary>Represents a single candidate response.</summary>
    public class Candidate
    {
        /// <summary>Gets or sets the content of the candidate.</summary>
        public Content? Content { get; set; }
    }

    /// <summary>Represents the content structure of a candidate.</summary>
    public class Content
    {
        /// <summary>Gets or sets the list of parts in the content.</summary>
        public List<Part>? Parts { get; set; }
    }

    /// <summary>Represents a specific part of the content, typically holding text.</summary>
    public class Part
    {
        /// <summary>Gets or sets the text generated by the model.</summary>
        public string? Text { get; set; }
    }
}
